apiVersion: v1
kind: Service
metadata:
  name: stock-checker
spec:
  ports:
  - name: stock-checker
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: stock-checker
  type: NodePort
